### ISSUE TITLE
KSP 0.24 Compatibility

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#130]
It seems likely that version 1.4.1 will also be the 0.24 compatibility release. Judging from the feature list we've seen so far, 0.24 compatibility will need the following steps:
- [x] Check the placement of the RemoteTech components in the new tech tree, particularly anything in the Flight Control branch.
- [x] Check the costs of all antennas; the devs said they're reviewing the costs of all the stock parts to make sure they fit the new system. (#141)
- [ ] Add support for gimbal roll to flight computer (can wait till later?)
- [x] Rebuild against the 0.24 libraries. (#146)
- [x] Bundle Module Manager 2.2.0 or later (#145)

These are the only issues I can foresee; did I miss anything major?
